name: 'Boilerplate Sync'
description: 'Sync project files from boilerplate repositories'
author: 'Your Name'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  sources:
    description: |
      YAML array of source repositories. Each source contains:
        - source: GitHub repo in 'owner/repo' format
        - ref: (optional) git ref (branch, tag, commit SHA)
        - source-token: (optional) token for private repos (falls back to github-token)
        - default_files: (optional) simple list of files where local_path === source_path
        - file_pairs: (optional) array of file mappings with local_path and optional source_path
      At least one of default_files or file_pairs is required per source.
      Example:
        sources: |
          - source: org/boilerplate
            ref: main
            default_files:
              - .eslintrc.js
              - .prettierrc
            file_pairs:
              - local_path: .github/workflows/ci.yml
                source_path: workflows/ci.yml
          - source: org/private-templates
            source-token: ${{ secrets.PRIVATE_PAT }}
            default_files:
              - config.json
    required: true

  github-token:
    description: 'GitHub token for accessing source repos'
    required: true
    default: ${{ github.token }}

  create-missing:
    description: 'Create project files that do not exist yet'
    required: false
    default: 'true'

  fail-on-error:
    description: 'Fail the action if any file sync fails'
    required: false
    default: 'false'

outputs:
  has-changes:
    description: 'Whether any files were updated (true/false)'

  updated-count:
    description: 'Number of files successfully updated'

  failed-count:
    description: 'Number of files that failed to sync'

  skipped-count:
    description: 'Number of files skipped (unchanged)'

  summary:
    description: 'JSON summary of all sync operations'

runs:
  using: 'node20'
  main: 'dist/index.js'
