name: 'Boilerplate Sync'
description: 'Sync project files from boilerplate repositories and create a PR with updates'
author: 'Your Name'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  sources:
    description: |
      YAML array of source repositories. Each source contains:
        - source: GitHub repo in 'owner/repo' format
        - ref: (optional) git ref (branch, tag, commit SHA) - applies to all files from this source
        - files: array of file mappings, each with:
          - local_path: path in this repo to update
          - source_path: (optional) path to file in source repo, defaults to local_path
      Example:
        sources: |
          - source: org/boilerplate
            ref: main
            files:
              - local_path: .github/workflows/ci.yml
                source_path: workflows/ci.yml
              - local_path: .eslintrc.js
    required: true

  github-token:
    description: 'GitHub token for creating PRs in this repo'
    required: true
    default: ${{ github.token }}

  source-token:
    description: 'GitHub token for accessing source repos (if private). Defaults to github-token.'
    required: false

  create-missing:
    description: 'Create project files that do not exist yet'
    required: false
    default: 'true'

  fail-on-error:
    description: 'Fail the action if any file sync fails'
    required: false
    default: 'false'

  pr-title:
    description: 'Title for the created PR'
    required: false
    default: 'chore: sync boilerplate files'

  pr-labels:
    description: 'Comma-separated labels to add to the PR'
    required: false
    default: 'boilerplate,automated'

  pr-branch:
    description: 'Branch name prefix for the PR (run ID will be appended)'
    required: false
    default: 'boilerplate-sync'

  commit-message:
    description: 'Commit message for file updates'
    required: false
    default: 'chore: sync boilerplate files'

  schedule:
    description: 'Cron expression for documentation purposes (actual scheduling is done in workflow file)'
    required: false

outputs:
  has-changes:
    description: 'Whether any files were updated (true/false)'

  updated-count:
    description: 'Number of files successfully updated'

  failed-count:
    description: 'Number of files that failed to sync'

  skipped-count:
    description: 'Number of files skipped (unchanged)'

  pr-number:
    description: 'Pull request number if created'

  pr-url:
    description: 'Pull request URL if created'

  summary:
    description: 'JSON summary of all sync operations'

runs:
  using: 'node20'
  main: 'dist/index.js'
