import { describe, it, expect } from 'vitest';
import { generatePrBody, generateCommitMessage, generateStepSummary } from '../src/report';
import type { SyncSummary, SyncResult, FileSyncConfig } from '../src/sources/types';

function createConfig(overrides: Partial<FileSyncConfig> = {}): FileSyncConfig {
  return {
    project: '.eslintrc.js',
    source: 'my-org/boilerplate',
    path: '.eslintrc.js',
    ...overrides,
  };
}

function createResult(
  status: 'updated' | 'created' | 'skipped' | 'failed',
  overrides: Partial<SyncResult> = {}
): SyncResult {
  return {
    config: createConfig(overrides.config),
    status,
    resolvedRef: 'main',
    ...overrides,
  };
}

function createSummary(overrides: Partial<SyncSummary> = {}): SyncSummary {
  return {
    updated: [],
    created: [],
    skipped: [],
    failed: [],
    total: 0,
    hasChanges: false,
    allFailed: false,
    ...overrides,
  };
}

describe('generatePrBody', () => {
  it('generates body with updated files', () => {
    const summary = createSummary({
      updated: [
        createResult('updated', {
          config: { project: '.eslintrc.js', source: 'org/repo', path: '.eslintrc.js' },
          resolvedRef: 'main',
        }),
      ],
      total: 1,
      hasChanges: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('## 🔄 Boilerplate Sync');
    expect(body).toContain('### ✅ Updated (1 file)');
    expect(body).toContain('`.eslintrc.js`');
    expect(body).toContain('`org/repo`');
    expect(body).toContain('main');
  });

  it('generates body with created files', () => {
    const summary = createSummary({
      created: [
        createResult('created', {
          config: { project: 'new-file.js', source: 'org/repo', path: 'new-file.js' },
        }),
      ],
      total: 1,
      hasChanges: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('### 🆕 Created (1 file)');
    expect(body).toContain('`new-file.js`');
  });

  it('generates body with skipped files', () => {
    const summary = createSummary({
      skipped: [
        createResult('skipped', {
          config: { project: 'unchanged.js', source: 'org/repo', path: 'unchanged.js' },
        }),
      ],
      total: 1,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('### ⏭️ Skipped (1 file)');
    expect(body).toContain('No changes detected');
  });

  it('generates body with failed files', () => {
    const summary = createSummary({
      failed: [
        createResult('failed', {
          config: { project: 'missing.js', source: 'org/repo', path: 'missing.js' },
          error: 'File not found',
        }),
      ],
      total: 1,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('### ❌ Failed (1 file)');
    expect(body).toContain('File not found');
  });

  it('includes all-failed warning', () => {
    const summary = createSummary({
      failed: [createResult('failed', { error: 'Error' })],
      total: 1,
      allFailed: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('⚠️ **All files failed to sync.**');
    expect(body).toContain('draft');
  });

  it('generates body with mixed results', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      created: [createResult('created')],
      skipped: [createResult('skipped')],
      failed: [createResult('failed', { error: 'Some error' })],
      total: 4,
      hasChanges: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('### ✅ Updated');
    expect(body).toContain('### 🆕 Created');
    expect(body).toContain('### ⏭️ Skipped');
    expect(body).toContain('### ❌ Failed');
  });

  it('escapes markdown special characters', () => {
    const summary = createSummary({
      failed: [
        createResult('failed', {
          config: { project: 'file|name.js', source: 'org/repo', path: 'file.js' },
          error: 'Error with | pipe',
        }),
      ],
      total: 1,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('\\|');
  });

  it('includes footer with action link', () => {
    const summary = createSummary();
    const body = generatePrBody(summary);

    expect(body).toContain('Generated by');
    expect(body).toContain('boilerplate-sync');
  });

  it('pluralizes correctly for single file', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      total: 1,
      hasChanges: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('(1 file)');
    expect(body).not.toContain('(1 files)');
  });

  it('pluralizes correctly for multiple files', () => {
    const summary = createSummary({
      updated: [createResult('updated'), createResult('updated')],
      total: 2,
      hasChanges: true,
    });

    const body = generatePrBody(summary);

    expect(body).toContain('(2 files)');
  });
});

describe('generateCommitMessage', () => {
  it('returns base message with counts', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      created: [createResult('created')],
      total: 2,
      hasChanges: true,
    });

    const message = generateCommitMessage(summary, 'chore: sync');

    expect(message).toBe('chore: sync (1 updated, 1 created)');
  });

  it('includes failed count', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      failed: [createResult('failed')],
      total: 2,
      hasChanges: true,
    });

    const message = generateCommitMessage(summary, 'chore: sync');

    expect(message).toBe('chore: sync (1 updated, 1 failed)');
  });

  it('returns special message for all-failed', () => {
    const summary = createSummary({
      failed: [createResult('failed')],
      total: 1,
      allFailed: true,
    });

    const message = generateCommitMessage(summary, 'chore: sync');

    expect(message).toBe('chore: sync [all files failed]');
  });

  it('returns base message when no changes', () => {
    const summary = createSummary({
      skipped: [createResult('skipped')],
      total: 1,
    });

    const message = generateCommitMessage(summary, 'chore: sync');

    expect(message).toBe('chore: sync');
  });
});

describe('generateStepSummary', () => {
  it('generates summary table', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      created: [createResult('created')],
      skipped: [createResult('skipped')],
      failed: [createResult('failed')],
      total: 4,
      hasChanges: true,
    });

    const stepSummary = generateStepSummary(summary);

    expect(stepSummary).toContain('# Boilerplate Sync Results');
    expect(stepSummary).toContain('| ✅ Updated | 1 |');
    expect(stepSummary).toContain('| 🆕 Created | 1 |');
    expect(stepSummary).toContain('| ⏭️ Skipped | 1 |');
    expect(stepSummary).toContain('| ❌ Failed | 1 |');
    expect(stepSummary).toContain('| **Total** | **4** |');
  });

  it('shows PR will be created when changes detected', () => {
    const summary = createSummary({
      updated: [createResult('updated')],
      total: 1,
      hasChanges: true,
    });

    const stepSummary = generateStepSummary(summary);

    expect(stepSummary).toContain('✅ Changes detected - PR will be created');
  });

  it('shows draft PR message when all failed', () => {
    const summary = createSummary({
      failed: [createResult('failed')],
      total: 1,
      allFailed: true,
    });

    const stepSummary = generateStepSummary(summary);

    expect(stepSummary).toContain('⚠️ All files failed - draft PR will be created');
  });

  it('shows no PR needed when no changes', () => {
    const summary = createSummary({
      skipped: [createResult('skipped')],
      total: 1,
    });

    const stepSummary = generateStepSummary(summary);

    expect(stepSummary).toContain('ℹ️ No changes detected - no PR needed');
  });
});
