import type { SyncResult, SyncSummary } from './sources/types';

/**
 * Escape characters that would break markdown tables
 * Only escaping pipe (|) and backslash (\\) since those break table structure
 */
function escapeMarkdown(text: string): string {
  return text.replace(/[|\\]/g, '\\$&');
}

/**
 * Format a single result row for the table
 */
function formatResultRow(result: SyncResult): string {
  const file = `\`${escapeMarkdown(result.config.local_path)}\``;
  const source = `\`${escapeMarkdown(result.config.source)}\``;
  const ref = result.resolvedRef ?? result.config.ref ?? '_default_';
  
  return `| ${file} | ${source} | ${escapeMarkdown(ref)} |`;
}

/**
 * Format a failed result row
 */
function formatFailedRow(result: SyncResult): string {
  const file = `\`${escapeMarkdown(result.config.local_path)}\``;
  const error = escapeMarkdown(result.error ?? 'Unknown error');
  
  return `| ${file} | ${error} |`;
}

/**
 * Format a skipped result row
 */
function formatSkippedRow(result: SyncResult): string {
  const file = `\`${escapeMarkdown(result.config.local_path)}\``;
  const reason = result.error ?? 'No changes detected';
  
  return `| ${file} | ${escapeMarkdown(reason)} |`;
}

/**
 * Generate the PR body markdown
 */
export function generatePrBody(summary: SyncSummary, schedule?: string): string {
  const lines: string[] = [];

  lines.push('## 🔄 Boilerplate Sync');
  lines.push('');
  lines.push('This PR updates project files from their boilerplate sources.');
  lines.push('');

  // Add schedule information if provided
  if (schedule) {
    lines.push(`**Schedule:** \`${schedule}\``);
    lines.push('');
  }

  // Updated files section
  if (summary.updated.length > 0) {
    lines.push(`### ✅ Updated (${summary.updated.length} file${summary.updated.length === 1 ? '' : 's'})`);
    lines.push('');
    lines.push('| File | Source | Ref |');
    lines.push('|------|--------|-----|');
    for (const result of summary.updated) {
      lines.push(formatResultRow(result));
    }
    lines.push('');
  }

  // Created files section
  if (summary.created.length > 0) {
    lines.push(`### 🆕 Created (${summary.created.length} file${summary.created.length === 1 ? '' : 's'})`);
    lines.push('');
    lines.push('| File | Source | Ref |');
    lines.push('|------|--------|-----|');
    for (const result of summary.created) {
      lines.push(formatResultRow(result));
    }
    lines.push('');
  }

  // Skipped files section
  if (summary.skipped.length > 0) {
    lines.push(`### ⏭️ Skipped (${summary.skipped.length} file${summary.skipped.length === 1 ? '' : 's'})`);
    lines.push('');
    lines.push('| File | Reason |');
    lines.push('|------|--------|');
    for (const result of summary.skipped) {
      lines.push(formatSkippedRow(result));
    }
    lines.push('');
  }

  // Failed files section
  if (summary.failed.length > 0) {
    lines.push(`### ❌ Failed (${summary.failed.length} file${summary.failed.length === 1 ? '' : 's'})`);
    lines.push('');
    lines.push('| File | Error |');
    lines.push('|------|-------|');
    for (const result of summary.failed) {
      lines.push(formatFailedRow(result));
    }
    lines.push('');
    
    // Add warning if all files failed
    if (summary.allFailed) {
      lines.push('> ⚠️ **All files failed to sync.** This PR is marked as draft. Please investigate the errors above.');
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [boilerplate-sync](https://github.com/your-org/boilerplate-sync)*');

  return lines.join('\n');
}

/**
 * Generate a summary for GitHub Actions step summary
 */
export function generateStepSummary(summary: SyncSummary): string {
  const lines: string[] = [];

  lines.push('# Boilerplate Sync Results');
  lines.push('');
  
  lines.push('| Status | Count |');
  lines.push('|--------|-------|');
  lines.push(`| ✅ Updated | ${summary.updated.length} |`);
  lines.push(`| 🆕 Created | ${summary.created.length} |`);
  lines.push(`| ⏭️ Skipped | ${summary.skipped.length} |`);
  lines.push(`| ❌ Failed | ${summary.failed.length} |`);
  lines.push(`| **Total** | **${summary.total}** |`);
  lines.push('');

  if (summary.hasChanges) {
    lines.push('✅ Changes detected - PR will be created');
  } else if (summary.allFailed) {
    lines.push('⚠️ All files failed - draft PR will be created');
  } else {
    lines.push('ℹ️ No changes detected - no PR needed');
  }

  return lines.join('\n');
}

/**
 * Generate commit message based on summary
 */
export function generateCommitMessage(
  summary: SyncSummary,
  baseMessage: string
): string {
  if (summary.allFailed) {
    return `${baseMessage} [all files failed]`;
  }

  const parts: string[] = [];
  
  if (summary.updated.length > 0) {
    parts.push(`${summary.updated.length} updated`);
  }
  if (summary.created.length > 0) {
    parts.push(`${summary.created.length} created`);
  }
  if (summary.failed.length > 0) {
    parts.push(`${summary.failed.length} failed`);
  }

  if (parts.length > 0) {
    return `${baseMessage} (${parts.join(', ')})`;
  }

  return baseMessage;
}
